#!/bin/bash

NODE_ENV=test scripts/create_test_database && node scripts/migrate --up && node ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha && node ./node_modules/istanbul/lib/cli.js check-coverage --statements 90 --functions 90 --branches 90 --lines 90
