#!/bin/bash

NODE_ENV=test scripts/create_test_database && node scripts/migrate --up | node_modules/.bin/bunyan && node ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha && node ./node_modules/istanbul/lib/cli.js check-coverage --statements 70 --functions 60 --branches 55 --lines 70
