#!/bin/bash

NODE_ENV=test scripts/create_test_database && \
NODE_ENV=test node scripts/migrate --up | node_modules/.bin/bunyan && \
NODE_ENV=test node ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha && \
NODE_ENV=test node ./node_modules/istanbul/lib/cli.js check-coverage --statements 75 --functions 60 --branches 70 --lines 75
